/** Static data: Vietnam provinces and districts */

export interface Province {
  code: string;
  name: string;
}

export interface District {
  code: string;
  name: string;
}

export const PROVINCES: Province[] = [
  { code: 'HCM', name: 'Hồ Chí Minh' },
  { code: 'HNI', name: 'Hà Nội' },
  { code: 'DNG', name: 'Đà Nẵng' },
  { code: 'CTH', name: 'Cần Thơ' },
  { code: 'HPH', name: 'Hải Phòng' },
  { code: 'BDG', name: 'Bình Dương' },
  { code: 'DNA', name: 'Đồng Nai' },
  { code: 'LAN', name: 'Long An' },
  { code: 'TGG', name: 'Tiền Giang' },
  { code: 'AGG', name: 'An Giang' },
  { code: 'HBH', name: 'Hòa Bình' },
  { code: 'YBY', name: 'Yên Bái' },
  { code: 'DTU', name: 'Điện Biên' },
  { code: 'LCU', name: 'Lai Châu' },
  { code: 'SLA', name: 'Sơn La' },
  { code: 'LSN', name: 'Lào Cai' },
  { code: 'HGG', name: 'Hà Giang' },
  { code: 'CBG', name: 'Cao Bằng' },
  { code: 'BKN', name: 'Bắc Kạn' },
  { code: 'TNN', name: 'Tuyên Quang' },
  { code: 'LDG', name: 'Lạng Sơn' },
  { code: 'QNI', name: 'Quảng Ninh' },
  { code: 'BGB', name: 'Bắc Giang' },
  { code: 'PTO', name: 'Phú Thọ' },
  { code: 'VPC', name: 'Vĩnh Phúc' },
  { code: 'BNH', name: 'Bắc Ninh' },
  { code: 'HDB', name: 'Hải Dương' },
  { code: 'HYG', name: 'Hưng Yên' },
  { code: 'TNH', name: 'Thái Nguyên' },
  { code: 'TBH', name: 'Thái Bình' },
  { code: 'HAM', name: 'Hà Nam' },
  { code: 'NAN', name: 'Nam Định' },
  { code: 'NBH', name: 'Ninh Bình' },
  { code: 'THA', name: 'Thanh Hóa' },
  { code: 'NAN2', name: 'Nghệ An' },
  { code: 'HTH', name: 'Hà Tĩnh' },
  { code: 'QBH', name: 'Quảng Bình' },
  { code: 'QTI', name: 'Quảng Trị' },
  { code: 'TTH', name: 'Thừa Thiên Huế' },
  { code: 'QNM', name: 'Quảng Nam' },
  { code: 'QNI2', name: 'Quảng Ngãi' },
  { code: 'BDH', name: 'Bình Định' },
  { code: 'PYN', name: 'Phú Yên' },
  { code: 'KHA', name: 'Khánh Hòa' },
  { code: 'NTN', name: 'Ninh Thuận' },
  { code: 'BTH', name: 'Bình Thuận' },
  { code: 'KON', name: 'Kon Tum' },
  { code: 'GLI', name: 'Gia Lai' },
  { code: 'DLK', name: 'Đắk Lắk' },
  { code: 'DNO', name: 'Đắk Nông' },
  { code: 'LDG2', name: 'Lâm Đồng' },
  { code: 'BPH', name: 'Bình Phước' },
  { code: 'TNN2', name: 'Tây Ninh' },
  { code: 'BRV', name: 'Bà Rịa - Vũng Tàu' },
  { code: 'VTU', name: 'Vĩnh Long' },
  { code: 'BTR', name: 'Bến Tre' },
  { code: 'TRV', name: 'Trà Vinh' },
  { code: 'STG', name: 'Sóc Trăng' },
  { code: 'DVP', name: 'Đồng Tháp' },
  { code: 'HGG2', name: 'Hậu Giang' },
  { code: 'BGG', name: 'Bạc Liêu' },
  { code: 'CMU', name: 'Cà Mau' },
  { code: 'KGG', name: 'Kiên Giang' },
];

export const DISTRICTS: Record<string, District[]> = {
  HCM: [
    { code: 'HCM-Q1', name: 'Quận 1' },
    { code: 'HCM-Q3', name: 'Quận 3' },
    { code: 'HCM-Q4', name: 'Quận 4' },
    { code: 'HCM-Q5', name: 'Quận 5' },
    { code: 'HCM-Q6', name: 'Quận 6' },
    { code: 'HCM-Q7', name: 'Quận 7' },
    { code: 'HCM-Q8', name: 'Quận 8' },
    { code: 'HCM-Q10', name: 'Quận 10' },
    { code: 'HCM-Q11', name: 'Quận 11' },
    { code: 'HCM-Q12', name: 'Quận 12' },
    { code: 'HCM-BTH', name: 'Bình Thạnh' },
    { code: 'HCM-GVP', name: 'Gò Vấp' },
    { code: 'HCM-PNH', name: 'Phú Nhuận' },
    { code: 'HCM-TBH', name: 'Tân Bình' },
    { code: 'HCM-TPH', name: 'Tân Phú' },
    { code: 'HCM-BTN', name: 'Bình Tân' },
    { code: 'HCM-TDC', name: 'Thủ Đức' },
    { code: 'HCM-NBE', name: 'Nhà Bè' },
    { code: 'HCM-HMN', name: 'Hóc Môn' },
    { code: 'HCM-CCH', name: 'Củ Chi' },
    { code: 'HCM-CGO', name: 'Cần Giờ' },
    { code: 'HCM-BCH', name: 'Bình Chánh' },
  ],
  HNI: [
    { code: 'HNI-BDH', name: 'Ba Đình' },
    { code: 'HNI-HKM', name: 'Hoàn Kiếm' },
    { code: 'HNI-HBT', name: 'Hai Bà Trưng' },
    { code: 'HNI-DDa', name: 'Đống Đa' },
    { code: 'HNI-TH', name: 'Tây Hồ' },
    { code: 'HNI-CGY', name: 'Cầu Giấy' },
    { code: 'HNI-TXN', name: 'Thanh Xuân' },
    { code: 'HNI-HMI', name: 'Hoàng Mai' },
    { code: 'HNI-LBN', name: 'Long Biên' },
    { code: 'HNI-NTL', name: 'Nam Từ Liêm' },
    { code: 'HNI-BTL', name: 'Bắc Từ Liêm' },
    { code: 'HNI-HDG', name: 'Hà Đông' },
    { code: 'HNI-STL', name: 'Sơn Tây' },
    { code: 'HNI-BAI', name: 'Ba Vì' },
    { code: 'HNI-PHO', name: 'Phúc Thọ' },
    { code: 'HNI-DTI', name: 'Đan Phượng' },
    { code: 'HNI-HNC', name: 'Hoài Đức' },
    { code: 'HNI-QOI', name: 'Quốc Oai' },
    { code: 'HNI-TST', name: 'Thạch Thất' },
    { code: 'HNI-CKE', name: 'Chương Mỹ' },
    { code: 'HNI-TLI', name: 'Thanh Liêm' },
    { code: 'HNI-MTH', name: 'Mỹ Đức' },
    { code: 'HNI-URN', name: 'Ứng Hòa' },
    { code: 'HNI-PLY', name: 'Phú Lương' },
    { code: 'HNI-TMN', name: 'Thường Tín' },
    { code: 'HNI-PXN', name: 'Phú Xuyên' },
    { code: 'HNI-EON', name: 'Gia Lâm' },
    { code: 'HNI-DNH', name: 'Đông Anh' },
    { code: 'HNI-SIN', name: 'Sóc Sơn' },
    { code: 'HNI-MGO', name: 'Mê Linh' },
  ],
  DNG: [
    { code: 'DNG-HL', name: 'Hải Châu' },
    { code: 'DNG-TKP', name: 'Thanh Khê' },
    { code: 'DNG-STS', name: 'Sơn Trà' },
    { code: 'DNG-NGH', name: 'Ngũ Hành Sơn' },
    { code: 'DNG-LCH', name: 'Liên Chiểu' },
    { code: 'DNG-CLE', name: 'Cẩm Lệ' },
    { code: 'DNG-HVN', name: 'Hòa Vang' },
  ],
  CTH: [
    { code: 'CTH-NK', name: 'Ninh Kiều' },
    { code: 'CTH-BT', name: 'Bình Thủy' },
    { code: 'CTH-CT', name: 'Cái Răng' },
    { code: 'CTH-OH', name: 'Ô Môn' },
    { code: 'CTH-TC', name: 'Thốt Nốt' },
    { code: 'CTH-VT', name: 'Vĩnh Thạnh' },
    { code: 'CTH-CL', name: 'Cờ Đỏ' },
    { code: 'CTH-PD', name: 'Phong Điền' },
    { code: 'CTH-TL', name: 'Thới Lai' },
  ],
  HPH: [
    { code: 'HPH-HBM', name: 'Hồng Bàng' },
    { code: 'HPH-NQN', name: 'Ngô Quyền' },
    { code: 'HPH-LBN', name: 'Lê Chân' },
    { code: 'HPH-HAN', name: 'Hải An' },
    { code: 'HPH-KAO', name: 'Kiến An' },
    { code: 'HPH-DDN', name: 'Đồ Sơn' },
    { code: 'HPH-DHO', name: 'Dương Kinh' },
    { code: 'HPH-TDNG', name: 'Thuỷ Nguyên' },
    { code: 'HPH-ADO', name: 'An Dương' },
    { code: 'HPH-ALO', name: 'An Lão' },
    { code: 'HPH-KTY', name: 'Kiến Thuỵ' },
    { code: 'HPH-TCH', name: 'Tiên Lãng' },
    { code: 'HPH-VBU', name: 'Vĩnh Bảo' },
    { code: 'HPH-CGA', name: 'Cát Hải' },
    { code: 'HPH-BLG', name: 'Bạch Long Vĩ' },
  ],
  BDG: [
    { code: 'BDG-TDM', name: 'Thủ Dầu Một' },
    { code: 'BDG-BNG', name: 'Bến Cát' },
    { code: 'BDG-TAN', name: 'Tân Uyên' },
    { code: 'BDG-DAI', name: 'Dĩ An' },
    { code: 'BDG-THA', name: 'Thuận An' },
    { code: 'BDG-BAU', name: 'Bàu Bàng' },
    { code: 'BDG-BLG', name: 'Bắc Tân Uyên' },
    { code: 'BDG-DAM', name: 'Dầu Tiếng' },
    { code: 'BDG-PHG', name: 'Phú Giáo' },
  ],
  DNA: [
    { code: 'DNA-BGH', name: 'Biên Hòa' },
    { code: 'DNA-LKH', name: 'Long Khánh' },
    { code: 'DNA-DHO', name: 'Định Quán' },
    { code: 'DNA-TQN', name: 'Tân Phú' },
    { code: 'DNA-VCU', name: 'Vĩnh Cửu' },
    { code: 'DNA-XLO', name: 'Xuân Lộc' },
    { code: 'DNA-CQN', name: 'Cẩm Mỹ' },
    { code: 'DNA-LTH', name: 'Long Thành' },
    { code: 'DNA-NBN', name: 'Nhơn Trạch' },
    { code: 'DNA-THQ', name: 'Thống Nhất' },
    { code: 'DNA-TRG', name: 'Trảng Bom' },
  ],
  LAN: [
    { code: 'LAN-TAN', name: 'Tân An' },
    { code: 'LAN-KCG', name: 'Kiến Tường' },
    { code: 'LAN-TDU', name: 'Tân Thạnh' },
    { code: 'LAN-THN', name: 'Thạnh Hóa' },
    { code: 'LAN-MTO', name: 'Mộc Hóa' },
    { code: 'LAN-VHT', name: 'Vĩnh Hưng' },
    { code: 'LAN-THH', name: 'Tân Hưng' },
    { code: 'LAN-BCH', name: 'Bến Lức' },
    { code: 'LAN-DTH', name: 'Đức Hòa' },
    { code: 'LAN-DHE', name: 'Đức Huệ' },
    { code: 'LAN-CLG', name: 'Cần Giuộc' },
    { code: 'LAN-CDN', name: 'Cần Đước' },
    { code: 'LAN-CHL', name: 'Châu Thành' },
    { code: 'LAN-THU', name: 'Thủ Thừa' },
  ],
  TGG: [
    { code: 'TGG-MTO', name: 'Mỹ Tho' },
    { code: 'TGG-GCG', name: 'Gò Công' },
    { code: 'TGG-CGH', name: 'Cai Lậy' },
    { code: 'TGG-CGY', name: 'Cái Bè' },
    { code: 'TGG-CTH', name: 'Châu Thành' },
    { code: 'TGG-CGN', name: 'Chợ Gạo' },
    { code: 'TGG-GCE', name: 'Gò Công Đông' },
    { code: 'TGG-GCT', name: 'Gò Công Tây' },
    { code: 'TGG-TPN', name: 'Tân Phú Đông' },
    { code: 'TGG-TFU', name: 'Tân Phước' },
  ],
  AGG: [
    { code: 'AGG-LXN', name: 'Long Xuyên' },
    { code: 'AGG-CHU', name: 'Châu Đốc' },
    { code: 'AGG-TFU', name: 'Tân Châu' },
    { code: 'AGG-CPH', name: 'Châu Phú' },
    { code: 'AGG-CTH', name: 'Châu Thành' },
    { code: 'AGG-CTI', name: 'Chợ Mới' },
    { code: 'AGG-TGI', name: 'Thoại Sơn' },
    { code: 'AGG-TIN', name: 'Tri Tôn' },
    { code: 'AGG-PBH', name: 'Phú Tân' },
    { code: 'AGG-ANP', name: 'An Phú' },
    { code: 'AGG-TCU', name: 'Tịnh Biên' },
  ],
  HBH: [
    { code: 'HBH-HBH', name: 'Hòa Bình' },
    { code: 'HBH-DDG', name: 'Đà Bắc' },
    { code: 'HBH-MAI', name: 'Mai Châu' },
    { code: 'HBH-MLU', name: 'Mường La' },
    { code: 'HBH-TAN', name: 'Tân Lạc' },
    { code: 'HBH-CAO', name: 'Cao Phong' },
    { code: 'HBH-KBU', name: 'Kim Bôi' },
    { code: 'HBH-LCH', name: 'Lạc Thủy' },
    { code: 'HBH-LSN', name: 'Lạc Sơn' },
    { code: 'HBH-YTY', name: 'Yên Thủy' },
  ],
  YBY: [
    { code: 'YBY-YBY', name: 'Yên Bái' },
    { code: 'YBY-NGI', name: 'Nghĩa Lộ' },
    { code: 'YBY-LCH', name: 'Lục Yên' },
    { code: 'YBY-MCI', name: 'Mù Cang Chải' },
    { code: 'YBY-TRG', name: 'Trạm Tấu' },
    { code: 'YBY-VAN', name: 'Văn Chấn' },
    { code: 'YBY-VYN', name: 'Văn Yên' },
    { code: 'YBY-YBN', name: 'Yên Bình' },
    { code: 'YBY-TNH', name: 'Trấn Yên' },
  ],
  DTU: [
    { code: 'DTU-DBP', name: 'Điện Biên Phủ' },
    { code: 'DTU-MTY', name: 'Mường Tè' },
    { code: 'DTU-DBH', name: 'Điện Biên' },
    { code: 'DTU-DDE', name: 'Điện Biên Đông' },
    { code: 'DTU-TAY', name: 'Tủa Chùa' },
    { code: 'DTU-MLA', name: 'Mường Lay' },
    { code: 'DTU-MNH', name: 'Mường Nhé' },
    { code: 'DTU-MCH', name: 'Mường Chà' },
    { code: 'DTU-NUI', name: 'Nậm Pồ' },
  ],
  LCU: [
    { code: 'LCU-LCH', name: 'Lai Châu' },
    { code: 'LCU-TAM', name: 'Tam Đường' },
    { code: 'LCU-PHO', name: 'Phong Thổ' },
    { code: 'LCU-SHO', name: 'Sìn Hồ' },
    { code: 'LCU-NNH', name: 'Nậm Nhùn' },
    { code: 'LCU-MTH', name: 'Mường Tè' },
    { code: 'LCU-TDU', name: 'Than Uyên' },
  ],
  SLA: [
    { code: 'SLA-SLA', name: 'Sơn La' },
    { code: 'SLA-QBU', name: 'Quỳnh Nhai' },
    { code: 'SLA-TSG', name: 'Thuận Châu' },
    { code: 'SLA-MLA', name: 'Mường La' },
    { code: 'SLA-BCH', name: 'Bắc Yên' },
    { code: 'SLA-PHU', name: 'Phù Yên' },
    { code: 'SLA-MCH', name: 'Mộc Châu' },
    { code: 'SLA-YCH', name: 'Yên Châu' },
    { code: 'SLA-MAI', name: 'Mai Sơn' },
    { code: 'SLA-SDN', name: 'Sông Mã' },
    { code: 'SLA-SMA', name: 'Sốp Cộp' },
    { code: 'SLA-VHO', name: 'Vân Hồ' },
  ],
  LSN: [
    { code: 'LSN-LSN', name: 'Lào Cai' },
    { code: 'LSN-BTH', name: 'Bắc Hà' },
    { code: 'LSN-BAT', name: 'Bảo Thắng' },
    { code: 'LSN-BYN', name: 'Bảo Yên' },
    { code: 'LSN-MCH', name: 'Mường Khương' },
    { code: 'LSN-SMA', name: 'Sa Pa' },
    { code: 'LSN-SIN', name: 'Si Ma Cai' },
    { code: 'LSN-VBN', name: 'Văn Bàn' },
  ],
  HGG: [
    { code: 'HGG-HGG', name: 'Hà Giang' },
    { code: 'HGG-DNV', name: 'Đồng Văn' },
    { code: 'HGG-MEO', name: 'Mèo Vạc' },
    { code: 'HGG-YMI', name: 'Yên Minh' },
    { code: 'HGG-QBH', name: 'Quản Bạ' },
    { code: 'HGG-VXN', name: 'Vị Xuyên' },
    { code: 'HGG-BCU', name: 'Bắc Mê' },
    { code: 'HGG-HGN', name: 'Hoàng Su Phì' },
    { code: 'HGG-XMN', name: 'Xín Mần' },
    { code: 'HGG-BSN', name: 'Bắc Quang' },
    { code: 'HGG-QBN', name: 'Quang Bình' },
  ],
  CBG: [
    { code: 'CBG-CBG', name: 'Cao Bằng' },
    { code: 'CBG-BCH', name: 'Bảo Lạc' },
    { code: 'CBG-BLA', name: 'Bảo Lâm' },
    { code: 'CBG-HAN', name: 'Hà Quảng' },
    { code: 'CBG-NGN', name: 'Nguyên Bình' },
    { code: 'CBG-QHO', name: 'Quảng Hòa' },
    { code: 'CBG-THO', name: 'Thông Nông' },
    { code: 'CBG-TAN', name: 'Trùng Khánh' },
    { code: 'CBG-HAG', name: 'Hạ Lang' },
    { code: 'CBG-TRU', name: 'Trà Lĩnh' },
  ],
  BKN: [
    { code: 'BKN-BKN', name: 'Bắc Kạn' },
    { code: 'BKN-BCH', name: 'Bạch Thông' },
    { code: 'BKN-CDN', name: 'Chợ Đồn' },
    { code: 'BKN-CMI', name: 'Chợ Mới' },
    { code: 'BKN-NGS', name: 'Ngân Sơn' },
    { code: 'BKN-NRN', name: 'Na Rì' },
    { code: 'BKN-PPH', name: 'Pác Nặm' },
  ],
  TNN: [
    { code: 'TNN-TQG', name: 'Tuyên Quang' },
    { code: 'TNN-LM', name: 'Lâm Bình' },
    { code: 'TNN-NAS', name: 'Na Hang' },
    { code: 'TNN-CIU', name: 'Chiêm Hóa' },
    { code: 'TNN-HYN', name: 'Hàm Yên' },
    { code: 'TNN-YSN', name: 'Yên Sơn' },
    { code: 'TNN-SYN', name: 'Sơn Dương' },
  ],
  LDG: [
    { code: 'LDG-LSN', name: 'Lạng Sơn' },
    { code: 'LDG-TIN', name: 'Tràng Định' },
    { code: 'LDG-BLC', name: 'Bình Gia' },
    { code: 'LDG-VLN', name: 'Văn Lãng' },
    { code: 'LDG-CAO', name: 'Cao Lộc' },
    { code: 'LDG-LOC', name: 'Lộc Bình' },
    { code: 'LDG-DNG', name: 'Đình Lập' },
    { code: 'LDG-CHI', name: 'Chi Lăng' },
    { code: 'LDG-HUY', name: 'Hữu Lũng' },
    { code: 'LDG-BAN', name: 'Bắc Sơn' },
    { code: 'LDG-VQN', name: 'Văn Quan' },
  ],
  QNI: [
    { code: 'QNI-HL', name: 'Hạ Long' },
    { code: 'QNI-CAM', name: 'Cẩm Phả' },
    { code: 'QNI-UAI', name: 'Uông Bí' },
    { code: 'QNI-MON', name: 'Móng Cái' },
    { code: 'QNI-CVN', name: 'Cô Tô' },
    { code: 'QNI-VDN', name: 'Vân Đồn' },
    { code: 'QNI-HON', name: 'Hoành Bồ' },
    { code: 'QNI-QYN', name: 'Quảng Yên' },
    { code: 'QNI-DDO', name: 'Đông Triều' },
    { code: 'QNI-HHO', name: 'Hải Hà' },
    { code: 'QNI-DNK', name: 'Đầm Hà' },
    { code: 'QNI-TIN', name: 'Tiên Yên' },
    { code: 'QNI-BIU', name: 'Bình Liêu' },
  ],
  BGB: [
    { code: 'BGB-BGG', name: 'Bắc Giang' },
    { code: 'BGB-HHO', name: 'Hiệp Hòa' },
    { code: 'BGB-LNG', name: 'Lạng Giang' },
    { code: 'BGB-LCH', name: 'Lục Nam' },
    { code: 'BGB-LNI', name: 'Lục Ngạn' },
    { code: 'BGB-SON', name: 'Sơn Động' },
    { code: 'BGB-TAN', name: 'Tân Yên' },
    { code: 'BGB-VIY', name: 'Việt Yên' },
    { code: 'BGB-YDG', name: 'Yên Dũng' },
    { code: 'BGB-YTH', name: 'Yên Thế' },
  ],
  PTO: [
    { code: 'PTO-VTO', name: 'Việt Trì' },
    { code: 'PTO-PHT', name: 'Phú Thọ' },
    { code: 'PTO-DAK', name: 'Đoan Hùng' },
    { code: 'PTO-HAO', name: 'Hạ Hòa' },
    { code: 'PTO-TAN', name: 'Thanh Ba' },
    { code: 'PTO-CGI', name: 'Cẩm Khê' },
    { code: 'PTO-YLA', name: 'Yên Lập' },
    { code: 'PTO-CTH', name: 'Cẩm Thủy' },
    { code: 'PTO-PHN', name: 'Phù Ninh' },
    { code: 'PTO-LTH', name: 'Lâm Thao' },
    { code: 'PTO-TNH', name: 'Tam Nông' },
    { code: 'PTO-TLU', name: 'Tân Sơn' },
  ],
  VPC: [
    { code: 'VPC-VYN', name: 'Vĩnh Yên' },
    { code: 'VPC-PHU', name: 'Phúc Yên' },
    { code: 'VPC-LPH', name: 'Lập Thạch' },
    { code: 'VPC-SPH', name: 'Sông Lô' },
    { code: 'VPC-TNH', name: 'Tam Dương' },
    { code: 'VPC-TDO', name: 'Tam Đảo' },
    { code: 'VPC-BBN', name: 'Bình Xuyên' },
    { code: 'VPC-VTH', name: 'Vĩnh Tường' },
    { code: 'VPC-YLG', name: 'Yên Lạc' },
  ],
  BNH: [
    { code: 'BNH-BNH', name: 'Bắc Ninh' },
    { code: 'BNH-YPG', name: 'Yên Phong' },
    { code: 'BNH-QVO', name: 'Quế Võ' },
    { code: 'BNH-TAN', name: 'Tiên Du' },
    { code: 'BNH-TAS', name: 'Từ Sơn' },
    { code: 'BNH-TBN', name: 'Thuận Thành' },
    { code: 'BNH-GBN', name: 'Gia Bình' },
    { code: 'BNH-LTI', name: 'Lương Tài' },
  ],
  HDB: [
    { code: 'HDB-HDG', name: 'Hải Dương' },
    { code: 'HDB-CHI', name: 'Chí Linh' },
    { code: 'HDB-KMN', name: 'Kinh Môn' },
    { code: 'HDB-NAM', name: 'Nam Sách' },
    { code: 'HDB-BIG', name: 'Bình Giang' },
    { code: 'HDB-CIN', name: 'Cẩm Giàng' },
    { code: 'HDB-GOI', name: 'Gia Lộc' },
    { code: 'HDB-TIN', name: 'Tứ Kỳ' },
    { code: 'HDB-TAN', name: 'Thanh Hà' },
    { code: 'HDB-NIH', name: 'Ninh Giang' },
    { code: 'HDB-TNI', name: 'Thanh Miện' },
  ],
  HYG: [
    { code: 'HYG-HYG', name: 'Hưng Yên' },
    { code: 'HYG-MHO', name: 'Mỹ Hào' },
    { code: 'HYG-ANT', name: 'Ân Thi' },
    { code: 'HYG-KDG', name: 'Khoái Châu' },
    { code: 'HYG-KGN', name: 'Kim Động' },
    { code: 'HYG-PHO', name: 'Phù Cừ' },
    { code: 'HYG-TLU', name: 'Tiên Lữ' },
    { code: 'HYG-VGN', name: 'Văn Giang' },
    { code: 'HYG-VLM', name: 'Văn Lâm' },
    { code: 'HYG-YMY', name: 'Yên Mỹ' },
  ],
  TNH: [
    { code: 'TNH-TNG', name: 'Thái Nguyên' },
    { code: 'TNH-SGN', name: 'Sông Công' },
    { code: 'TNH-PBN', name: 'Phổ Yên' },
    { code: 'TNH-DBN', name: 'Định Hóa' },
    { code: 'TNH-DOI', name: 'Đồng Hỷ' },
    { code: 'TNH-PDU', name: 'Phú Lương' },
    { code: 'TNH-PHI', name: 'Phú Bình' },
    { code: 'TNH-VNG', name: 'Võ Nhai' },
    { code: 'TNH-DGN', name: 'Đại Từ' },
  ],
  TBH: [
    { code: 'TBH-TBH', name: 'Thái Bình' },
    { code: 'TBH-DBO', name: 'Đông Hưng' },
    { code: 'TBH-HTH', name: 'Hưng Hà' },
    { code: 'TBH-KSN', name: 'Kiến Xương' },
    { code: 'TBH-QHN', name: 'Quỳnh Phụ' },
    { code: 'TBH-TSN', name: 'Tiền Hải' },
    { code: 'TBH-VTH', name: 'Vũ Thư' },
    { code: 'TBH-TRG', name: 'Thái Thụy' },
  ],
  HAM: [
    { code: 'HAM-PHI', name: 'Phủ Lý' },
    { code: 'HAM-BLU', name: 'Bình Lục' },
    { code: 'HAM-DDg', name: 'Duy Tiên' },
    { code: 'HAM-KBG', name: 'Kim Bảng' },
    { code: 'HAM-LYN', name: 'Lý Nhân' },
    { code: 'HAM-TNH', name: 'Thanh Liêm' },
  ],
  NAN: [
    { code: 'NAN-NDH', name: 'Nam Định' },
    { code: 'NAN-GVN', name: 'Giao Thủy' },
    { code: 'NAN-HHU', name: 'Hải Hậu' },
    { code: 'NAN-MLC', name: 'Mỹ Lộc' },
    { code: 'NAN-NCH', name: 'Nam Trực' },
    { code: 'NAN-NBI', name: 'Nghĩa Hưng' },
    { code: 'NAN-TRG', name: 'Trực Ninh' },
    { code: 'NAN-VBN', name: 'Vụ Bản' },
    { code: 'NAN-YKH', name: 'Ý Yên' },
    { code: 'NAN-XTU', name: 'Xuân Trường' },
  ],
  NBH: [
    { code: 'NBH-NBH', name: 'Ninh Bình' },
    { code: 'NBH-TLU', name: 'Tam Điệp' },
    { code: 'NBH-GVN', name: 'Gia Viễn' },
    { code: 'NBH-HTH', name: 'Hoa Lư' },
    { code: 'NBH-KHS', name: 'Kim Sơn' },
    { code: 'NBH-NHU', name: 'Nho Quan' },
    { code: 'NBH-YKH', name: 'Yên Khánh' },
    { code: 'NBH-YMO', name: 'Yên Mô' },
  ],
  THA: [
    { code: 'THA-THA', name: 'Thanh Hóa' },
    { code: 'THA-SMN', name: 'Sầm Sơn' },
    { code: 'THA-BGR', name: 'Bỉm Sơn' },
    { code: 'THA-MAI', name: 'Mường Lát' },
    { code: 'THA-QHO', name: 'Quan Hóa' },
    { code: 'THA-BSn', name: 'Bá Thước' },
    { code: 'THA-QSN', name: 'Quan Sơn' },
    { code: 'THA-LCH', name: 'Lang Chánh' },
    { code: 'THA-NXN', name: 'Ngọc Lặc' },
    { code: 'THA-CTH', name: 'Cẩm Thủy' },
    { code: 'THA-TIN', name: 'Thạch Thành' },
    { code: 'THA-HCH', name: 'Hà Trung' },
    { code: 'THA-VYN', name: 'Vĩnh Lộc' },
    { code: 'THA-YDH', name: 'Yên Định' },
    { code: 'THA-TYN', name: 'Thọ Xuân' },
    { code: 'THA-TIN2', name: 'Thường Xuân' },
    { code: 'THA-TGG', name: 'Triệu Sơn' },
    { code: 'THA-THO', name: 'Thiệu Hóa' },
    { code: 'THA-HHO', name: 'Hoằng Hóa' },
    { code: 'THA-HNG', name: 'Hậu Lộc' },
    { code: 'THA-NGL', name: 'Nga Sơn' },
    { code: 'THA-QXN', name: 'Quảng Xương' },
    { code: 'THA-NNH', name: 'Nông Cống' },
    { code: 'THA-DDn', name: 'Đông Sơn' },
    { code: 'THA-TPH', name: 'Tĩnh Gia' },
  ],
  NAN2: [
    { code: 'NAN2-VAN', name: 'Vinh' },
    { code: 'NAN2-CSM', name: 'Cửa Lò' },
    { code: 'NAN2-THI', name: 'Thái Hòa' },
    { code: 'NAN2-KSN', name: 'Kỳ Sơn' },
    { code: 'NAN2-TKI', name: 'Tương Dương' },
    { code: 'NAN2-CNH', name: 'Con Cuông' },
    { code: 'NAN2-ATN', name: 'Anh Sơn' },
    { code: 'NAN2-NAN', name: 'Nghĩa Đàn' },
    { code: 'NAN2-QHO', name: 'Quỳ Hợp' },
    { code: 'NAN2-QCH', name: 'Quỳ Châu' },
    { code: 'NAN2-QPN', name: 'Quỳnh Lưu' },
    { code: 'NAN2-HTH', name: 'Hoàng Mai' },
    { code: 'NAN2-TAN', name: 'Thanh Chương' },
    { code: 'NAN2-NGN', name: 'Nghi Lộc' },
    { code: 'NAN2-NAn', name: 'Nam Đàn' },
    { code: 'NAN2-HNG', name: 'Hưng Nguyên' },
    { code: 'NAN2-DDo', name: 'Đô Lương' },
    { code: 'NAN2-YTH', name: 'Yên Thành' },
    { code: 'NAN2-DCH', name: 'Diễn Châu' },
  ],
  HTH: [
    { code: 'HTH-HTH', name: 'Hà Tĩnh' },
    { code: 'HTH-HHO', name: 'Hồng Lĩnh' },
    { code: 'HTH-HHu', name: 'Hương Sơn' },
    { code: 'HTH-DCH', name: 'Đức Thọ' },
    { code: 'HTH-VQN', name: 'Vũ Quang' },
    { code: 'HTH-NGXn', name: 'Nghi Xuân' },
    { code: 'HTH-CLo', name: 'Can Lộc' },
    { code: 'HTH-HKH', name: 'Hương Khê' },
    { code: 'HTH-TXn', name: 'Thạch Hà' },
    { code: 'HTH-CMo', name: 'Cẩm Xuyên' },
    { code: 'HTH-KAn', name: 'Kỳ Anh' },
    { code: 'HTH-LHo', name: 'Lộc Hà' },
  ],
  QBH: [
    { code: 'QBH-DBH', name: 'Đồng Hới' },
    { code: 'QBH-MHo', name: 'Minh Hóa' },
    { code: 'QBH-TGo', name: 'Tuyên Hóa' },
    { code: 'QBH-QTr', name: 'Quảng Trạch' },
    { code: 'QBH-BAn', name: 'Bố Trạch' },
    { code: 'QBH-QNi', name: 'Quảng Ninh' },
    { code: 'QBH-LEt', name: 'Lệ Thủy' },
    { code: 'QBH-BATh', name: 'Ba Đồn' },
  ],
  QTI: [
    { code: 'QTI-DTh', name: 'Đông Hà' },
    { code: 'QTI-QTr', name: 'Quảng Trị' },
    { code: 'QTI-VLi', name: 'Vĩnh Linh' },
    { code: 'QTI-HHo', name: 'Hướng Hóa' },
    { code: 'QTI-KAn', name: 'Gio Linh' },
    { code: 'QTI-CAm', name: 'Cam Lộ' },
    { code: 'QTI-TBi', name: 'Triệu Phong' },
    { code: 'QTI-HHa', name: 'Hải Lăng' },
    { code: 'QTI-DKn', name: 'Đakrông' },
    { code: 'QTI-CSo', name: 'Cồn Cỏ' },
  ],
  TTH: [
    { code: 'TTH-HUE', name: 'Huế' },
    { code: 'TTH-PAn', name: 'Phong Điền' },
    { code: 'TTH-QDi', name: 'Quảng Điền' },
    { code: 'TTH-HHo', name: 'Hương Trà' },
    { code: 'TTH-PHu', name: 'Phú Vang' },
    { code: 'TTH-HThuy', name: 'Hương Thủy' },
    { code: 'TTH-PLoc', name: 'Phú Lộc' },
    { code: 'TTH-NaD', name: 'Nam Đông' },
    { code: 'TTH-ALD', name: 'A Lưới' },
  ],
  QNM: [
    { code: 'QNM-TAm', name: 'Tam Kỳ' },
    { code: 'QNM-HAn', name: 'Hội An' },
    { code: 'QNM-TGi', name: 'Tây Giang' },
    { code: 'QNM-DDon', name: 'Đông Giang' },
    { code: 'QNM-DGi', name: 'Đại Lộc' },
    { code: 'QNM-DBan', name: 'Điện Bàn' },
    { code: 'QNM-DAnh', name: 'Duy Xuyên' },
    { code: 'QNM-QSon', name: 'Quế Sơn' },
    { code: 'QNM-NuiTh', name: 'Nui Thành' },
    { code: 'QNM-PTr', name: 'Phú Ninh' },
    { code: 'QNM-HGi', name: 'Hiệp Đức' },
    { code: 'QNM-TPhuo', name: 'Thăng Bình' },
    { code: 'QNM-TPhu', name: 'Tiên Phước' },
    { code: 'QNM-BDon', name: 'Bắc Trà My' },
    { code: 'QNM-NTM', name: 'Nam Trà My' },
    { code: 'QNM-PStr', name: 'Phước Sơn' },
    { code: 'QNM-NPhuc', name: 'Nam Giang' },
  ],
  QNI2: [
    { code: 'QNI2-QNg', name: 'Quảng Ngãi' },
    { code: 'QNI2-BScn', name: 'Bình Sơn' },
    { code: 'QNI2-TBin', name: 'Trà Bồng' },
    { code: 'QNI2-SonT', name: 'Sơn Tịnh' },
    { code: 'QNI2-TuNg', name: 'Tư Nghĩa' },
    { code: 'QNI2-SonH', name: 'Sơn Hà' },
    { code: 'QNI2-SonT2', name: 'Sơn Tây' },
    { code: 'QNI2-MinL', name: 'Minh Long' },
    { code: 'QNI2-NghiH', name: 'Nghĩa Hành' },
    { code: 'QNI2-ModDuc', name: 'Mộ Đức' },
    { code: 'QNI2-DucPh', name: 'Đức Phổ' },
    { code: 'QNI2-BaTo', name: 'Ba Tơ' },
    { code: 'QNI2-LyCon', name: 'Lý Sơn' },
  ],
  BDH: [
    { code: 'BDH-QNon', name: 'Quy Nhơn' },
    { code: 'BDH-AnLa', name: 'An Lão' },
    { code: 'BDH-HoaiA', name: 'Hoài Ân' },
    { code: 'BDH-HoaiN', name: 'Hoài Nhơn' },
    { code: 'BDH-PhMy', name: 'Phù Mỹ' },
    { code: 'BDH-VCnh', name: 'Vĩnh Thạnh' },
    { code: 'BDH-TayS', name: 'Tây Sơn' },
    { code: 'BDH-PhCat', name: 'Phù Cát' },
    { code: 'BDH-AnNhon', name: 'An Nhơn' },
    { code: 'BDH-TuPh', name: 'Tuy Phước' },
    { code: 'BDH-VaDe', name: 'Vân Canh' },
  ],
  PYN: [
    { code: 'PYN-TuyHo', name: 'Tuy Hòa' },
    { code: 'PYN-SonH', name: 'Sơn Hòa' },
    { code: 'PYN-SongH', name: 'Sông Hinh' },
    { code: 'PYN-TayH', name: 'Tây Hòa' },
    { code: 'PYN-DongH', name: 'Đông Hòa' },
    { code: 'PYN-PhHo', name: 'Phú Hòa' },
    { code: 'PYN-TuyAn', name: 'Tuy An' },
    { code: 'PYN-DongX', name: 'Đồng Xuân' },
    { code: 'PYN-PhongB', name: 'Song Cầu' },
  ],
  KHA: [
    { code: 'KHA-NTr', name: 'Nha Trang' },
    { code: 'KHA-CamR', name: 'Cam Ranh' },
    { code: 'KHA-KhHo', name: 'Khánh Vĩnh' },
    { code: 'KHA-KhSon', name: 'Khánh Sơn' },
    { code: 'KHA-VanNi', name: 'Vạn Ninh' },
    { code: 'KHA-ElHo', name: 'El Hoa' },
    { code: 'KHA-NiHo', name: 'Ninh Hòa' },
    { code: 'KHA-CamLam', name: 'Cam Lâm' },
    { code: 'KHA-TruSa', name: 'Trường Sa' },
  ],
  NTN: [
    { code: 'NTN-PhRan', name: 'Phan Rang - Tháp Chàm' },
    { code: 'NTN-NiSon', name: 'Ninh Sơn' },
    { code: 'NTN-NiHai', name: 'Ninh Hải' },
    { code: 'NTN-NiPhuo', name: 'Ninh Phước' },
    { code: 'NTN-BacAi', name: 'Bác Ái' },
    { code: 'NTN-ThuanB', name: 'Thuận Bắc' },
    { code: 'NTN-ThuanN', name: 'Thuận Nam' },
  ],
  BTH: [
    { code: 'BTH-PhThiet', name: 'Phan Thiết' },
    { code: 'BTH-LaGi', name: 'La Gi' },
    { code: 'BTH-TuyPhon', name: 'Tuy Phong' },
    { code: 'BTH-BacBinh', name: 'Bắc Bình' },
    { code: 'BTH-HamThu', name: 'Hàm Thuận Bắc' },
    { code: 'BTH-HamThuN', name: 'Hàm Thuận Nam' },
    { code: 'BTH-TaiBH', name: 'Tánh Linh' },
    { code: 'BTH-DucLin', name: 'Đức Linh' },
    { code: 'BTH-HamTan', name: 'Hàm Tân' },
    { code: 'BTH-PhuQui', name: 'Phú Quý' },
  ],
  KON: [
    { code: 'KON-KonTum', name: 'Kon Tum' },
    { code: 'KON-DakGle', name: 'Đắk Glei' },
    { code: 'KON-NghinhA', name: 'Ngọc Hồi' },
    { code: 'KON-DakTo', name: 'Đắk Tô' },
    { code: 'KON-KonPlo', name: 'Kon Plông' },
    { code: 'KON-KonRay', name: 'Kon Rẫy' },
    { code: 'KON-DakHa', name: 'Đắk Hà' },
    { code: 'KON-SaThay', name: 'Sa Thầy' },
    { code: 'KON-TuMoRo', name: 'Tu Mơ Rông' },
    { code: 'KON-IaHDri', name: 'Ia H\'Drai' },
  ],
  GLI: [
    { code: 'GLI-PleKu', name: 'Pleiku' },
    { code: 'GLI-AnKhe', name: 'An Khê' },
    { code: 'GLI-AYunPa', name: 'Ayun Pa' },
    { code: 'GLI-KBang', name: 'K\'Bang' },
    { code: 'GLI-DakDoa', name: 'Đắk Đoa' },
    { code: 'GLI-ChuPah', name: 'Chư Păh' },
    { code: 'GLI-IaGrai', name: 'Ia Grai' },
    { code: 'GLI-MangYan', name: 'Mang Yang' },
    { code: 'GLI-KongChr', name: 'Kông Chro' },
    { code: 'GLI-DucCo', name: 'Đức Cơ' },
    { code: 'GLI-ChuProng', name: 'Chư Prông' },
    { code: 'GLI-ChuSe', name: 'Chư Sê' },
    { code: 'GLI-DakPo', name: 'Đắk Pơ' },
    { code: 'GLI-IaPa', name: 'Ia Pa' },
    { code: 'GLI-KrPa', name: 'Krông Pa' },
    { code: 'GLI-PhuThien', name: 'Phú Thiện' },
    { code: 'GLI-ChuPuH', name: 'Chư Pưh' },
  ],
  DLK: [
    { code: 'DLK-BMT', name: 'Buôn Ma Thuột' },
    { code: 'DLK-BuonDon', name: 'Buôn Đôn' },
    { code: 'DLK-CuKuin', name: 'Cư Kuin' },
    { code: 'DLK-CuMgar', name: 'Cư M\'Gar' },
    { code: 'DLK-EaHleo', name: 'Ea H\'Leo' },
    { code: 'DLK-EaKar', name: 'Ea Kar' },
    { code: 'DLK-EaSup', name: 'Ea Súp' },
    { code: 'DLK-KrongAna', name: 'Krông Ana' },
    { code: 'DLK-KrongBuk', name: 'Krông Búk' },
    { code: 'DLK-KrongBong', name: 'Krông Bông' },
    { code: 'DLK-KrongNang', name: 'Krông Năng' },
    { code: 'DLK-KrongPac', name: 'Krông Pắc' },
    { code: 'DLK-MDrk', name: 'M\'Đrắk' },
    { code: 'DLK-LakH', name: 'Lắk' },
  ],
  DNO: [
    { code: 'DNO-GiaNghia', name: 'Gia Nghĩa' },
    { code: 'DNO-DakGlo', name: 'Đắk Glong' },
    { code: 'DNO-CuJut', name: 'Cư Jút' },
    { code: 'DNO-DakMil', name: 'Đắk Mil' },
    { code: 'DNO-KrongNo', name: 'Krông Nô' },
    { code: 'DNO-DakSong', name: 'Đắk Song' },
    { code: 'DNO-DakRLap', name: 'Đắk R\'Lấp' },
    { code: 'DNO-TuyDuc', name: 'Tuy Đức' },
  ],
  LDG2: [
    { code: 'LDG2-DaLat', name: 'Đà Lạt' },
    { code: 'LDG2-BaoLoc', name: 'Bảo Lộc' },
    { code: 'LDG2-DaHuoai', name: 'Đạ Huoai' },
    { code: 'LDG2-DaTeh', name: 'Đạ Tẻh' },
    { code: 'LDG2-CatTien', name: 'Cát Tiên' },
    { code: 'LDG2-BaoLam', name: 'Bảo Lâm' },
    { code: 'LDG2-DiLinh', name: 'Di Linh' },
    { code: 'LDG2-DonDuong', name: 'Đơn Dương' },
    { code: 'LDG2-DucTrong', name: 'Đức Trọng' },
    { code: 'LDG2-LacDuong', name: 'Lạc Dương' },
    { code: 'LDG2-LamHa', name: 'Lâm Hà' },
    { code: 'LDG2-DamRong', name: 'Đam Rông' },
  ],
  BPH: [
    { code: 'BPH-DongXoai', name: 'Đồng Xoài' },
    { code: 'BPH-BinhLong', name: 'Bình Long' },
    { code: 'BPH-PhuocLong', name: 'Phước Long' },
    { code: 'BPH-DongPhu', name: 'Đồng Phú' },
    { code: 'BPH-BuDangP', name: 'Bù Đăng' },
    { code: 'BPH-LapVO', name: 'Lộc Ninh' },
    { code: 'BPH-BuDopP', name: 'Bù Đốp' },
    { code: 'BPH-HoaBinh', name: 'Hớn Quản' },
    { code: 'BPH-ChonThanh', name: 'Chơn Thành' },
    { code: 'BPH-PhuRieng', name: 'Phú Riềng' },
  ],
  TNN2: [
    { code: 'TNN2-TayNinh', name: 'Tây Ninh' },
    { code: 'TNN2-TanBinh', name: 'Tân Biên' },
    { code: 'TNN2-TanChau', name: 'Tân Châu' },
    { code: 'TNN2-DuongMinhChau', name: 'Dương Minh Châu' },
    { code: 'TNN2-ChauThanh', name: 'Châu Thành' },
    { code: 'TNN2-HoaThanh', name: 'Hòa Thành' },
    { code: 'TNN2-GoaDau', name: 'Gò Dầu' },
    { code: 'TNN2-BenCau', name: 'Bến Cầu' },
    { code: 'TNN2-TrangBang', name: 'Trảng Bàng' },
  ],
  BRV: [
    { code: 'BRV-VungTau', name: 'Vũng Tàu' },
    { code: 'BRV-BaRia', name: 'Bà Rịa' },
    { code: 'BRV-ChauDuc', name: 'Châu Đức' },
    { code: 'BRV-XuyenMoc', name: 'Xuyên Mộc' },
    { code: 'BRV-LongDien', name: 'Long Điền' },
    { code: 'BRV-DatDo', name: 'Đất Đỏ' },
    { code: 'BRV-TanThanh', name: 'Tân Thành' },
    { code: 'BRV-ConDao', name: 'Côn Đảo' },
  ],
  VTU: [
    { code: 'VTU-VinhLong', name: 'Vĩnh Long' },
    { code: 'VTU-LongHo', name: 'Long Hồ' },
    { code: 'VTU-MangThit', name: 'Mang Thít' },
    { code: 'VTU-VungLiem', name: 'Vũng Liêm' },
    { code: 'VTU-TamBinh', name: 'Tam Bình' },
    { code: 'VTU-BinhMinh', name: 'Bình Minh' },
    { code: 'VTU-TraOn', name: 'Trà Ôn' },
    { code: 'VTU-BinhTan', name: 'Bình Tân' },
  ],
  BTR: [
    { code: 'BTR-BenTre', name: 'Bến Tre' },
    { code: 'BTR-ChauThanh', name: 'Châu Thành' },
    { code: 'BTR-ChoBLach', name: 'Chợ Lách' },
    { code: 'BTR-MoCAy', name: 'Mỏ Cày Bắc' },
    { code: 'BTR-MoCayN', name: 'Mỏ Cày Nam' },
    { code: 'BTR-GiongTrom', name: 'Giồng Trôm' },
    { code: 'BTR-BinhDai', name: 'Bình Đại' },
    { code: 'BTR-BaTriN', name: 'Ba Tri' },
    { code: 'BTR-ThanhPhu', name: 'Thạnh Phú' },
  ],
  TRV: [
    { code: 'TRV-TraVinh', name: 'Trà Vinh' },
    { code: 'TRV-CangLong', name: 'Càng Long' },
    { code: 'TRV-CauKe', name: 'Cầu Kè' },
    { code: 'TRV-TieuCan', name: 'Tiểu Cần' },
    { code: 'TRV-ChauThanh', name: 'Châu Thành' },
    { code: 'TRV-CauNgang', name: 'Cầu Ngang' },
    { code: 'TRV-TraCu', name: 'Trà Cú' },
    { code: 'TRV-Duyen Hai', name: 'Duyên Hải' },
  ],
  STG: [
    { code: 'STG-SocTrang', name: 'Sóc Trăng' },
    { code: 'STG-ChauThanh', name: 'Châu Thành' },
    { code: 'STG-KeSach', name: 'Kế Sách' },
    { code: 'STG-MyTu', name: 'Mỹ Tú' },
    { code: 'STG-CuLao', name: 'Cù Lao Dung' },
    { code: 'STG-LongPhu', name: 'Long Phú' },
    { code: 'STG-MyXuyen', name: 'Mỹ Xuyên' },
    { code: 'STG-NGanh', name: 'Ngã Năm' },
    { code: 'STG-ThanTrieu', name: 'Thạnh Trị' },
    { code: 'STG-ViThe', name: 'Vĩnh Châu' },
    { code: 'STG-TranDe', name: 'Trần Đề' },
  ],
  DVP: [
    { code: 'DVP-CaoLanh', name: 'Cao Lãnh' },
    { code: 'DVP-SaDec', name: 'Sa Đéc' },
    { code: 'DVP-HongNgu', name: 'Hồng Ngự' },
    { code: 'DVP-TanHong', name: 'Tân Hồng' },
    { code: 'DVP-HongNguD', name: 'Hồng Ngự (H.)' },
    { code: 'DVP-TamNong', name: 'Tam Nông' },
    { code: 'DVP-ThanhBinh', name: 'Thanh Bình' },
    { code: 'DVP-ChauThanh', name: 'Châu Thành' },
    { code: 'DVP-LapVo', name: 'Lấp Vò' },
    { code: 'DVP-LaiVung', name: 'Lai Vung' },
    { code: 'DVP-CaoLanhH', name: 'Cao Lãnh (H.)' },
  ],
  HGG2: [
    { code: 'HGG2-ViThanh', name: 'Vị Thanh' },
    { code: 'HGG2-NgaBay', name: 'Ngã Bảy' },
    { code: 'HGG2-ChauThanh', name: 'Châu Thành' },
    { code: 'HGG2-ChauThanhA', name: 'Châu Thành A' },
    { code: 'HGG2-PhungHiep', name: 'Phụng Hiệp' },
    { code: 'HGG2-ViBinh', name: 'Vị Bình' },
    { code: 'HGG2-LongMyH', name: 'Long Mỹ (H.)' },
    { code: 'HGG2-LongMy', name: 'Long Mỹ' },
  ],
  BGG: [
    { code: 'BGG-BacLieu', name: 'Bạc Liêu' },
    { code: 'BGG-HoaBinh', name: 'Hòa Bình' },
    { code: 'BGG-VinhLoi', name: 'Vĩnh Lợi' },
    { code: 'BGG-GiaNhia', name: 'Giá Rai' },
    { code: 'BGG-DongHai', name: 'Đông Hải' },
    { code: 'BGG-PhuocLong', name: 'Phước Long' },
    { code: 'BGG-HongDan', name: 'Hồng Dân' },
  ],
  CMU: [
    { code: 'CMU-CaMau', name: 'Cà Mau' },
    { code: 'CMU-UMinh', name: 'U Minh' },
    { code: 'CMU-ThoiBinh', name: 'Thới Bình' },
    { code: 'CMU-TranVanTh', name: 'Trần Văn Thời' },
    { code: 'CMU-CaiNuoc', name: 'Cái Nước' },
    { code: 'CMU-DamDoi', name: 'Đầm Dơi' },
    { code: 'CMU-NamCan', name: 'Năm Căn' },
    { code: 'CMU-PhuTan', name: 'Phú Tân' },
    { code: 'CMU-NgocHien', name: 'Ngọc Hiển' },
  ],
  KGG: [
    { code: 'KGG-RachGia', name: 'Rạch Giá' },
    { code: 'KGG-HaTien', name: 'Hà Tiên' },
    { code: 'KGG-KienLuong', name: 'Kiên Lương' },
    { code: 'KGG-HonDat', name: 'Hòn Đất' },
    { code: 'KGG-TanHiep', name: 'Tân Hiệp' },
    { code: 'KGG-ChauThanh', name: 'Châu Thành' },
    { code: 'KGG-GiongRieng', name: 'Giồng Riềng' },
    { code: 'KGG-GoQuao', name: 'Gò Quao' },
    { code: 'KGG-AnBien', name: 'An Biên' },
    { code: 'KGG-AnMinh', name: 'An Minh' },
    { code: 'KGG-VinhThuan', name: 'Vĩnh Thuận' },
    { code: 'KGG-PhuQuoc', name: 'Phú Quốc' },
    { code: 'KGG-KienHai', name: 'Kiên Hải' },
    { code: 'KGG-UMinh', name: 'U Minh Thượng' },
    { code: 'KGG-GiangThanh', name: 'Giang Thành' },
  ],
};
